### ISSUE TITLE
error

### ISSUE THREAD

**Issue by elmaslarry** [sneklingame/Rewards-GUI#6]
10:45:22 WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS monthly int' at line 1
[10:45:22 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[10:45:22 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[10:45:22 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[10:45:22 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[10:45:22 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[10:45:22 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:382)
[10:45:22 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
[10:45:22 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[10:45:22 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[10:45:22 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[10:45:22 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[10:45:22 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2620)
[10:45:22 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2570)
[10:45:22 WARN]:        at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:779)
[10:45:22 WARN]:        at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:622)
[10:45:22 WARN]:        at me.sneklingame.rewards.mysql.MySQL.createColumn(MySQL.java:70)
[10:45:22 WARN]:        at me.sneklingame.rewards.Rewards.setupMySQL(Rewards.java:100)
[10:45:22 WARN]:        at me.sneklingame.rewards.Rewards.setupDataStorageMethod(Rewards.java:127)
[10:45:22 WARN]:        at me.sneklingame.rewards.Rewards.onEnable(Rewards.java:47)
[10:45:22 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[10:45:22 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[10:45:22 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
[10:45:22 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
[10:45:22 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
[10:45:22 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:203)
[10:45:22 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
[10:45:22 WARN]:        at java.lang.Thread.run(Thread.java:748)
[10:45:22 WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS daily_vip int' at line 1
[10:45:22 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[10:45:22 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[10:45:22 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[10:45:22 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[10:45:22 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[10:45:22 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:382)
[10:45:22 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
[10:45:22 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[10:45:22 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[10:45:22 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[10:45:22 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[10:45:22 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2620)
[10:45:22 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2570)
[10:45:22 WARN]:        at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:779)
[10:45:22 WARN]:        at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:622)
[10:45:22 WARN]:        at me.sneklingame.rewards.mysql.MySQL.createColumn(MySQL.java:70)
[10:45:22 WARN]:        at me.sneklingame.rewards.Rewards.setupMySQL(Rewards.java:100)
[10:45:22 WARN]:        at me.sneklingame.rewards.Rewards.setupDataStorageMethod(Rewards.java:127)
[10:45:22 WARN]:        at me.sneklingame.rewards.Rewards.onEnable(Rewards.java:47)
[10:45:22 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[10:45:22 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[10:45:22 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
[10:45:22 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
[10:45:22 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
[10:45:22 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:203)
[10:45:22 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
[10:45:22 WARN]:        at java.lang.Thread.run(Thread.java:748)
[10:45:22 WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS weekly_vip int' at line 1
[10:45:22 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[10:45:22 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[10:45:22 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[10:45:22 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[10:45:22 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[10:45:22 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:382)
[10:45:22 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
[10:45:22 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[10:45:22 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[10:45:22 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[10:45:22 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[10:45:22 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2620)
[10:45:22 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2570)
[10:45:22 WARN]:        at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:779)
[10:45:22 WARN]:        at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:622)
[10:45:22 WARN]:        at me.sneklingame.rewards.mysql.MySQL.createColumn(MySQL.java:70)
[10:45:22 WARN]:        at me.sneklingame.rewards.Rewards.setupMySQL(Rewards.java:100)
[10:45:22 WARN]:        at me.sneklingame.rewards.Rewards.setupDataStorageMethod(Rewards.java:127)
[10:45:22 WARN]:        at me.sneklingame.rewards.Rewards.onEnable(Rewards.java:47)
[10:45:22 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[10:45:22 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[10:45:22 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
[10:45:22 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
[10:45:22 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
[10:45:22 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:203)
[10:45:22 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
[10:45:22 WARN]:        at java.lang.Thread.run(Thread.java:748)

**Comment by sneklingame** [comment]
Hey! I've checked and everything seems to be working on my side. What version of Minecraft is your server using? When did this happen? (during startup, on a certain command, etc.) Could you send me your config.yml?

**Comment by elmaslarry** [comment]
paperspigot 1.8.8
error onstartup and when i use commands of plugin

config: https://pastebin.com/1awLz21G

**Comment by sneklingame** [comment]
Well, first things first, you're trying to place all items in the same slot (`slot: 12`). 

The second thing is non-english characters like "★" or even "á". I suggest you remove them because they might be causing the issue, and even if they didn't they're still not going to display properly in the game.

The weird thing is, that even with your config.yml, I still wasn't able to recreate the exact same error as you pasted above. I was wondering, does this happen with the default config?

**Comment by elmaslarry** [comment]
snek what is the variable for player in the commands? for example i want to do:
- broadcast (player) has received her reward today

**Comment by sneklingame** [comment]
> snek what is the variable for player in the commands? for example i want to do:
> 
> * broadcast (player) has received her reward today

It's `%player%`, but keep in mind, that it can only be used when executing commands through the console.

**Comment by elmaslarry** [comment]
Okey! now i have a error on claim reward
https://pastebin.com/kDx4FNk6

**Comment by elmaslarry** [comment]
also on startup appear this
https://pastebin.com/sjp206qa

**Comment by elmaslarry** [comment]
my config 
https://pastebin.com/KAZGRJg0

**Comment by sneklingame** [comment]
Hi,
I tried using your config and everything is working perfectly, so whatever the issue might be, it's probably on your side. Make sure you have the latest version of the plugin and that your server is running Java 8. Try deleting the `players` table (or all tables if there are more) in your `rewards` database, then reload the server.

If this doesn't help, let me know and I'll look into it.

**Comment by elmaslarry** [comment]
i have tried but nothing. 

i use java 8 and paper 1.8.8

i have another question... i have planned to install the plugin in up to 30 lobbies, i have bad experience with other reward plugins that dont sync player rewards between servers or simply consume 600% of cpu on mysql request... this plugin is tested on large server? i mean i have more than 500 players per hour that will claim rewards in lobbies.

**Comment by sneklingame** [comment]
This is really weird. I honestly don't know what could be causing this issue. Does it throw errors if you use the default config?

Unfortunately, the plugin isn't tested for such large networks. I don't see why it shouldn't work though.

**Comment by elmaslarry** [comment]
with default config no errors but if change any message or touch something appear errors. 

plugin can sync rewards between servers ? i have planned to give money and i dont want that players can get rewards in each lobby only in one and sync in others

**Comment by sneklingame** [comment]
That is really really weird. What text-editor do you use to edit the config? Make sure to set encoding to UTF-8.

As long as all servers have the plugin installed and all of them use the same database, the plugin should be able to sync all data between servers.

**Comment by elmaslarry** [comment]
im using notepad++ but i edit other plugins and no issues!

**Comment by elmaslarry** [comment]
so sad

**Comment by sneklingame** [comment]
I've tried everything I could think of. I'm sorry but I can't help you.
